export const scopeOptions = [
  { label: "Global", value: "GLOBAL" },
  { label: "Country Specific", value: "COUNTRY" },
];

export const countryOptions = [
  { label: "United States", value: "US" },
  { label: "United Kingdom", value: "GB" },
  { label: "India", value: "IN" },
  { label: "Canada", value: "CA" },
  { label: "Germany", value: "DE" },
  { label: "France", value: "FR" },
  { label: "Australia", value: "AU" },
  { label: "Japan", value: "JP" },
  { label: "Brazil", value: "BR" },
  { label: "China", value: "CN" },
  { label: "United Arab Emirates", value: "AE" },
  { label: "Russia", value: "RU" },
  { label: "South Africa", value: "ZA" },
];

export const timezoneOptions = [
  { label: "UTC", value: "UTC" },
  { label: "America/New_York", value: "America/New_York" },
  { label: "America/Los_Angeles", value: "America/Los_Angeles" },
  { label: "Europe/London", value: "Europe/London" },
  { label: "Europe/Berlin", value: "Europe/Berlin" },
  { label: "Europe/Paris", value: "Europe/Paris" },
  { label: "Asia/Kolkata", value: "Asia/Kolkata" },
  { label: "Asia/Tokyo", value: "Asia/Tokyo" },
  { label: "Asia/Dubai", value: "Asia/Dubai" },
  { label: "Australia/Sydney", value: "Australia/Sydney" },
  { label: "America/Sao_Paulo", value: "America/Sao_Paulo" },
  { label: "Africa/Johannesburg", value: "Africa/Johannesburg" },
  { label: "Asia/Shanghai", value: "Asia/Shanghai" },
];

export const dateFormatOptions = [
  { label: "DD/MM/YYYY", value: "DD/MM/YYYY" },
  { label: "MM/DD/YYYY", value: "MM/DD/YYYY" },
  { label: "YYYY/MM/DD", value: "YYYY/MM/DD" },
  { label: "DD.MM.YYYY", value: "DD.MM.YYYY" },
  { label: "YYYY-MM-DD", value: "YYYY-MM-DD" },
  { label: "D MMM, YYYY", value: "D MMM, YYYY" },
  //   { label: "D MMM YYYY", value: "D MMM YYYY" },
  { label: "D MMMM, YYYY", value: "D MMMM, YYYY" },
  //   { label: "D MMMM YYYY", value: "D MMMM YYYY" },
  { label: "MMM D, YYYY", value: "MMM D, YYYY" },
  { label: "MMMM D, YYYY", value: "MMMM D, YYYY" },
];

export const timeFormatOptions = [
  { label: "12-hour (AM/PM) (7:18 AM)", value: "h:mm A" },
  { label: "12-hour (AM/PM) (07:18 AM)", value: "hh:mm A" },
  { label: "24-hour", value: "HH:mm" },
];

export const currencyOptions = [
  { label: "US Dollar (USD)", value: "USD" },
  { label: "Indian Rupee (INR)", value: "INR" },
  { label: "Euro (EUR)", value: "EUR" },
  { label: "British Pound (GBP)", value: "GBP" },
  { label: "Canadian Dollar (CAD)", value: "CAD" },
  { label: "Australian Dollar (AUD)", value: "AUD" },
  { label: "Japanese Yen (JPY)", value: "JPY" },
  { label: "Chinese Yuan (CNY)", value: "CNY" },
  { label: "Brazilian Real (BRL)", value: "BRL" },
  { label: "UAE Dirham (AED)", value: "AED" },
  { label: "Russian Ruble (RUB)", value: "RUB" },
  { label: "South African Rand (ZAR)", value: "ZAR" },
];

export const measurementSystemOptions = [
  { label: "Metric (meters, kilograms, Celsius)", value: "metric" },
  { label: "Imperial (miles, pounds, Fahrenheit)", value: "imperial" },
];

export const numberFormatOptions = [
  { label: "1,234.56", value: "1,234.56" },
  { label: "1.234,56", value: "1.234,56" },
  { label: "1 234,56", value: "1 234,56" },
  { label: "1,23,456.78 (India style)", value: "1,23,456.78" },
];

export const weekStartOptions = [
  { label: "Monday", value: "monday" },
  { label: "Sunday", value: "sunday" },
  { label: "Saturday", value: "saturday" },
];

export const regionalPresets = {
  US: {
    country: "US",
    timezone: "America/New_York",
    dateFormat: "MM/DD/YYYY",
    timeFormat: "hh:mm A",
    currency: "USD",
    measurementSystem: "imperial",
    numberFormat: "1,234.56",
    weekStart: "sunday",
  },
  GB: {
    country: "GB",
    timezone: "Europe/London",
    dateFormat: "DD/MM/YYYY",
    timeFormat: "HH:mm",
    currency: "GBP",
    measurementSystem: "metric",
    numberFormat: "1,234.56",
    weekStart: "monday",
  },
  IN: {
    country: "IN",
    timezone: "Asia/Kolkata",
    dateFormat: "DD/MM/YYYY",
    timeFormat: "hh:mm A",
    currency: "INR",
    measurementSystem: "metric",
    numberFormat: "1,23,456.78",
    weekStart: "monday",
  },
  CA: {
    country: "CA",
    timezone: "America/Toronto",
    dateFormat: "YYYY-MM-DD",
    timeFormat: "hh:mm A",
    currency: "CAD",
    measurementSystem: "metric",
    numberFormat: "1,234.56",
    weekStart: "sunday",
  },
  DE: {
    country: "DE",
    timezone: "Europe/Berlin",
    dateFormat: "DD.MM.YYYY",
    timeFormat: "HH:mm",
    currency: "EUR",
    measurementSystem: "metric",
    numberFormat: "1.234,56",
    weekStart: "monday",
  },
  FR: {
    country: "FR",
    timezone: "Europe/Paris",
    dateFormat: "DD/MM/YYYY",
    timeFormat: "HH:mm",
    currency: "EUR",
    measurementSystem: "metric",
    numberFormat: "1 234,56",
    weekStart: "monday",
  },
  AU: {
    country: "AU",
    timezone: "Australia/Sydney",
    dateFormat: "DD/MM/YYYY",
    timeFormat: "hh:mm A",
    currency: "AUD",
    measurementSystem: "metric",
    numberFormat: "1,234.56",
    weekStart: "monday",
  },
  JP: {
    country: "JP",
    timezone: "Asia/Tokyo",
    dateFormat: "YYYY/MM/DD",
    timeFormat: "HH:mm",
    currency: "JPY",
    measurementSystem: "metric",
    numberFormat: "1,234.56",
    weekStart: "sunday",
  },
  BR: {
    country: "BR",
    timezone: "America/Sao_Paulo",
    dateFormat: "DD/MM/YYYY",
    timeFormat: "HH:mm",
    currency: "BRL",
    measurementSystem: "metric",
    numberFormat: "1.234,56",
    weekStart: "sunday",
  },
  AE: {
    country: "AE",
    timezone: "Asia/Dubai",
    dateFormat: "DD/MM/YYYY",
    timeFormat: "HH:mm",
    currency: "AED",
    measurementSystem: "metric",
    numberFormat: "1,234.56",
    weekStart: "sunday",
  },
  CN: {
    country: "CN",
    timezone: "Asia/Shanghai",
    dateFormat: "YYYY/MM/DD",
    timeFormat: "HH:mm",
    currency: "CNY",
    measurementSystem: "metric",
    numberFormat: "1,234.56",
    weekStart: "monday",
  },
  RU: {
    country: "RU",
    timezone: "Europe/Moscow",
    dateFormat: "DD.MM.YYYY",
    timeFormat: "HH:mm",
    currency: "RUB",
    measurementSystem: "metric",
    numberFormat: "1 234,56",
    weekStart: "monday",
  },
  ZA: {
    country: "ZA",
    timezone: "Africa/Johannesburg",
    dateFormat: "YYYY/MM/DD",
    timeFormat: "HH:mm",
    currency: "ZAR",
    measurementSystem: "metric",
    numberFormat: "1,234.56",
    weekStart: "sunday",
  },
};
