
from fhir.resources.encounter import Encounter
from app.repository.encounter_repository import EncounterRepository

class EncounterService:
    def __init__(self, repository: EncounterRepository):
        self.repository = repository

    async def create_encounter(self, encounter_data: dict) -> Encounter:
        # ID will be auto-generated by database
        # Remove id from encounter_data if present to let DB handle it
        encounter_data.pop("id", None)
        
        # Pass dict directly to repository to avoid FHIR validation issues
        return await self.repository.create(encounter_data)

    async def get_encounter(self, encounter_id: int) -> Encounter:
        return await self.repository.get(encounter_id)

    async def list_encounters(self) -> list[Encounter]:
        return await self.repository.list()

    async def delete_encounter(self, encounter_id: int) -> bool:
        return await self.repository.delete(encounter_id)
