
from fhir.resources.encounter import Encounter
from app.repository.encounter_repository import EncounterRepository


class EncounterService:
    def __init__(self, repository: EncounterRepository):
        self.repository = repository

    async def create_encounter(self, encounter_data: dict) -> Encounter:
        # ID will be auto-generated by database
        encounter_data.pop("id", None)

        # Our EncounterCreateSchema already validates the input structure.
        # We skip fhir.resources validation here because it expects strict
        # FHIR R4 types (e.g., class as Coding, condition as list[Reference])
        # that differ from our simplified storage schema.
        return await self.repository.create(encounter_data)

    async def update_encounter(self, encounter_id: int, encounter_data: dict) -> Encounter:
        encounter_data.pop("id", None)
        return await self.repository.update(encounter_id, encounter_data)

    async def get_encounter(self, encounter_id: int) -> Encounter:
        return await self.repository.get(encounter_id)

    async def list_encounters(self) -> list[Encounter]:
        return await self.repository.list()

    async def delete_encounter(self, encounter_id: int) -> bool:
        return await self.repository.delete(encounter_id)
