from fhir.resources.patient import Patient
from app.repository.patient_repository import PatientRepository
from app.core.validation import validate_model
from app.schemas.resources import PatientCreateSchema, PatientResponseSchema


class PatientService:
    def __init__(self, repository: PatientRepository):
        self.repository = repository

    async def create_patient(self, patient_data: dict) -> PatientResponseSchema:
        # ID will be auto-generated by database
        # Remove id from patient_data if present to let DB handle it
        patient_data.pop("id", None)
        patient = validate_model(PatientCreateSchema, patient_data)
        return await self.repository.create(patient)

    async def update_patient(
        self, patient_id: int, patient_data: dict
    ) -> PatientResponseSchema:
        patient_data.pop("id", None)
        patient = validate_model(PatientCreateSchema, patient_data)
        return await self.repository.update(patient_id, patient)

    async def get_patient(self, patient_id: int) -> PatientResponseSchema:
        return await self.repository.get(patient_id)

    async def list_patients(self) -> list[PatientResponseSchema]:
        return await self.repository.list()

    async def delete_patient(self, patient_id: int) -> bool:
        return await self.repository.delete(patient_id)
