
from fhir.resources.patient import Patient
from app.repository.patient_repository import PatientRepository

class PatientService:
    def __init__(self, repository: PatientRepository):
        self.repository = repository

    async def create_patient(self, patient_data: dict) -> Patient:
        # ID will be auto-generated by database
        # Remove id from patient_data if present to let DB handle it
        patient_data.pop("id", None)
        
        patient = Patient.model_validate(patient_data)
        return await self.repository.create(patient)

    async def get_patient(self, patient_id: int) -> Patient:
        return await self.repository.get(patient_id)

    async def list_patients(self) -> list[Patient]:
        return await self.repository.list()

    async def delete_patient(self, patient_id: int) -> bool:
        return await self.repository.delete(patient_id)
