
from fhir.resources.practitioner import Practitioner
from app.repository.practitioner_repository import PractitionerRepository

class PractitionerService:
    def __init__(self, repository: PractitionerRepository):
        self.repository = repository

    async def create_practitioner(self, practitioner_data: dict) -> Practitioner:
        # ID will be auto-generated by database
        # Remove id from practitioner_data if present to let DB handle it
        practitioner_data.pop("id", None)
        
        practitioner = Practitioner.model_validate(practitioner_data)
        return await self.repository.create(practitioner)

    async def get_practitioner(self, practitioner_id: int) -> Practitioner:
        return await self.repository.get(practitioner_id)

    async def list_practitioners(self) -> list[Practitioner]:
        return await self.repository.list()

    async def delete_practitioner(self, practitioner_id: int) -> bool:
        return await self.repository.delete(practitioner_id)
